apiVersion: v1
data:
  REACT_APP_BACKEND_URI: aHR0cDovL2JhY2tlbmQ6NTAwMA==
kind: Secret
metadata:
  creationTimestamp: "2022-06-11T05:55:45Z"
  name: frontend-secret
  namespace: default
  resourceVersion: "980"
  uid: bd4c68ed-960f-46e3-8535-d0e4e4bf10e4
type: Opaque
