version: "3"
services: 
  mongodb:
    image: mongo:5.0.9
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
  backend:
    image: backend:1.0.0
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - .env.backend
  frontend:
    image: frontend:1.0.0
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - .env.frontend
